language: node_js
node_js:
  - "node"

before_install:
  - npm install
  - npm run start.ci

script:
  - node_modules/.bin/jest
  - npm run unit.test.coverage
  - node_modules/.bin/newman run tests/api/collection.json
